{% set name = "pdemtools" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdemtools-{{ version }}.tar.gz
  sha256: 3b0b49db4f46b13596109296bbb53ce598d0593a0985be98d0358ea07e111003

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - rioxarray
    - rasterio
    - geopandas
    - pandas
    - shapely
    - numpy
    - gdal
    - opencv
    - scipy
    - numba
    - pyarrow

test:
  imports:
    - pdemtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trchudley/pdemtools
  summary: Conveniently search, download, and preprocess ArcticDEM and REMA products.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://pdemtools.readthedocs.io/
  dev_url: https://github.com/trchudley/pdemtools

extra:
  recipe-maintainers:
    - trchudley
