{% set python_min = "3.10" %}
{% set name = "pdemtools" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdemtools-{{ version }}.tar.gz
  sha256: d3775b95b271033a21b6d73360e7c8063348c9e7a751678b18260859d3d99b15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - setuptools
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - rioxarray
    - rasterio
    - geopandas
    - pandas
    - shapely
    - numpy
    - gdal
    - opencv
    - scipy
    - numba
    - pyarrow
    - fiona

test:
  imports:
    - pdemtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trchudley/pdemtools
  summary: Conveniently search, download, and preprocess ArcticDEM and REMA products.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://pdemtools.readthedocs.io/
  dev_url: https://github.com/trchudley/pdemtools

extra:
  recipe-maintainers:
    - trchudley
